CREATE TABLE `posts` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `link` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `posts` (`id`, `title`, `content`, `link`) VALUES
(1, 'Check if value exists in Array - jQuery and JavaScript', 'You may be seen in many websites for example PushBullet,Facebook,SlideShare, etc. while allows the user to upload files by drag and dropping or select files using browse button.\n\nIn this tutorial, we will be implementing the similar type of feature in our web page for uploading. We are using jQuery, AJAX, and PHP for uploading. In jQuery we are some new events – drag enter,drag over, and drop.', 'http://makitweb.com/check-value-exists-array-jquery-javascript/'),
(2, 'How to Detect Browser Window is Active or not - JavaScript', 'This tutorial, guide how to you can verify your domain in Mailchimp. Whenever you try to send the newsletter with an email which contains domain name for example – newsletter@makitweb.com . In this case, you need to verify it and authenticate your domain.\n\nIn this tutorial, I am assuming that you have a MailChimp account, if you haven’t then you can signup for it and a website.', 'http://makitweb.com/how-to-detect-browser-window-active-or-not-javascript/'),
(3, 'Make Live Editable Table with jQuery AJAX', 'In this tutorial, we are learning How you can use PHP to read RSS feeds of the websites and showing recent post lists using it.\n\nA short introduction to RSS, What is it.\n\nRSS (Rich Site Summary) is a format which is used in many websites which allow web publisher to syndicates their latest posts or data automatically. It also benefits to people who want to receive latest posts updates from their favorite websites.', 'http://makitweb.com/make-live-editable-table-with-jquery-ajax/'),
(4, 'Make a Dropdown with Search Box using jQuery', 'In this tutorial, we are going to learn how to add like and unlike button within the post using jQuery, AJAX, and PHP.\n\nWhat we are gone build in this tutorial is – We will show the list of posts within this posts they have like and unlike button. It also has a label which shows how many like and unlike  get by post. Whenever user clicked on a button the value of label gets changed.', 'http://makitweb.com/make-a-dropdown-with-search-box-using-jquery/'),
(5, 'How to delete file with jQuery AJAX', 'We can open the file in a number of ways according to need For example - Writing, Reading, Adding more content to file, etc. Its file handling functions are little similar to C language.', 'http://makitweb.com/how-to-delete-file-with-jquery-ajax/'),
(6, 'How to Concatenate Multiple columns in MySQL', 'It is a quick tutorial on MongoDB and how you can install it on your Windows OS. We will also learn some basic commands in MongoDB for example, creating and dropping a Database, Creation of a collection and some more operations related to the collection.', 'http://makitweb.com/how-to-concatenate-multiple-columns-in-mysql/'),
(7, 'MySQL - Convert Unix Timestamp to Date Time', 'A module is a container which defines the functionality of the application which is represented by the ng-app directive. It helps us to define services, directives, filters, etc.\nAnd The role of controllers in Angular is to expose data to our view via $scope, and controllers contain logic to enhance view behavior.', 'http://makitweb.com/mysql-convert-unix-timestamp-to-date-time/'),
(8, 'How to include HTML page with jQuery', 'jsfiddle generally used for sharing, saving and embedding HTML, CSS, and JavaScript snippets.\r\njsfiddle allows us to add code snippet within our web pages and we can able to customize look and feel of code snippet like changing the visual theme, font color, code background, menu background.\r\n\r\njsfiddle will show JavaScript, HTML, CSS and Result tabs by default we can some of its tab if their no use of it by check and uncheck the checkbox follow with tab name. For example, if you are making code snippet in which we have only used HTML and CSS section and not done any JavaScript work in that case there is no need of display JavaScript tab with your web page.', 'http://makitweb.com/how-to-include-html-page-with-jquery/'),
(9, 'Custom Right Click Context menu with jQuery', 'AngularJS is a JavaScript MVC framework  developed by Google that lets you build well structured, easily testable,  declarative and maintainable front-end applications which provides solutions to  standard infrastructure concerns.', 'http://makitweb.com/custom-right-click-context-menu-with-jquery/'),
(10, 'Dynamically add and remove element with jQuery', 'Node.js is a very powerful JavaScript-based framework/platform built on Google Chrome''s JavaScript V8 Engine which makes it possible to run Javascript on the server side. It is used to develop I/O intensive web applications like video streaming sites, single-page applications, and other web applications. It is awesome for real time stuff for example if we use PHP for this then it is not good for this because it consumes a lot of memory. Using NPM — a tool that makes installing and managing Node modules — it’s quite easy to add many useful tools to your web development toolkit.', 'http://makitweb.com/dynamically-add-and-remove-element-with-jquery/'),
(11, 'How to Delete a value from an Array in JavaScript', 'While working with a loop in the program there may be some case where we want to terminate the loop or skip the loop block while some condition occurs. For handling this type of cases we use loop control statements.', 'http://makitweb.com/how-to-delete-value-from-array-in-javascript/');
